spring.config.import=optional:file:.env

# SERVER
server.address=0.0.0.0
server.port=${PORT:8080}

spring.application.name=sastracare
spring.main.web-application-type=servlet

# =========================
# DATABASE
# =========================
spring.datasource.url=${DB_URL:}
spring.datasource.username=${DB_USERNAME:}
spring.datasource.password=${DB_PASSWORD:}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# =========================
# JWT
# =========================
jwt.secret=${JWT_SECRET:}
jwt.expiration=86400000
jwt.access.expiry.minutes=1440
jwt.refresh.expiry.days=7

# =========================
# AI / HUGGINGFACE
# =========================
huggingface.api-key=${HF_API_KEY:}
huggingface.tts-url=${HF_TTS_URL:}
ai.service.base-url=${AI_BASE_URL:}

# =========================
# REDIS
# =========================
spring.data.redis.url=${REDIS_URL:}
spring.data.redis.timeout=60000
spring.data.redis.repositories.enabled=false

# =========================
# TWILIO
# =========================
twilio.account.sid=${TWILIO_ACCOUNT_SID:}
twilio.api.key=${TWILIO_API_KEY:}
twilio.api.secret=${TWILIO_API_SECRET:}
twilio.auth.token=${TWILIO_AUTH_TOKEN:}
twilio.phone.number=${TWILIO_PHONE_NUMBER:}

otp.expiry.minutes=1440

# =========================
# LOGGING
# =========================
logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.org.hibernate=INFO

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration